name: "Deploy to Balena"

on:
  push:
    tags:
      - "*.*.*"
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

env:
  BALENA_APP: gh_mattster98/balena-wifi-repeater

jobs:
  build:
    name: "Deploy-to-Balena"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: npm install

      - name: Upload updated lock file
        uses: actions/upload-artifact@v4
        with:
          name: package-lock.json
          path: package-lock.json
  
      - name: Update balena.yml
        uses: balena-io-experimental/balena.yml-action@main
        with:
          # Synchronise the GitHub README with the Balena Hub README
          sync_readme: true
          # If pushing a tag to deploy, use the same tag as the version number to display on Balena Hub
          sync_tag: true

      - name: Deploy to Balena
        uses: balena-io/deploy-to-balena-action@master
        with:
          balena_token: ${{ secrets.balena_token }}
          fleet: ${{ env.BALENA_APP }}
